FROM mharj/starmade_base:latest
MAINTAINER mharj
USER starmade
EXPOSE 4242 4242/udp
WORKDIR  /opt/starmade/StarMade
VOLUME ["/opt/starmade/StarMade/server-database"]
CMD /opt/starmade/StarMade/StarMade-dedicated-server-linux.sh
